Add navigator property to PullDownButton
notDmDrl/pull_down_button pull request #49
Opened 2024-06-11 01:26 UTC by gborges9

This PR introduces a new navigator property to the package, allowing users to specify a custom navigator when pushing a route. This enhancement is particularly useful for scenarios involving nested navigation.

2024-06-11 16:44 UTC, notDmDrl commented
Hi @gborges9, 

Before I look over this, I want to know why something like this will be useful since I have not seen anything like this for any menus or dialogs in the Flutter repo. My knowledge of custom navigators is non-existent 🥲.

Could you, by any chance, provide some screenshots or videos showing how this PR solves the problems you described in the PR message?

Thanks

2024-06-11 18:17 UTC, gborges9 commented
Hey @notDmDrl,

When using a nested navigator, it may not occupy the entire screen. This causes the popup menu to remain visible even if you click outside the navigator where the popup menu route was pushed.

Here's an example to illustrate the issue:
https://github.com/notDmDrl/pull_down_button/assets/37756671/18994ef7-08c5-4be3-aef2-5fd890dd1a4a

One straightforward solution to this edge case is to provide the root navigator manually:
https://github.com/notDmDrl/pull_down_button/assets/37756671/57adda62-44cf-48c1-b8cd-cee790e3e85e


Alternatively, you could render the menu as an overlay entry and use a custom widget to wrap the app and handle the menu overlay entries. However, this approach would require some refactoring

2024-06-11 19:11 UTC, notDmDrl commented
> is to provide the root navigator manually

Wouldn't it be better to just expose the `rootNavigator` property of `Navigator.of(context)` in `_showMenu` as it defaults to `false`?

2024-06-11 19:13 UTC, notDmDrl requested changes
Overall looks good, only minor stuff code-wise.

For overall implementation please see https://github.com/notDmDrl/pull_down_button/pull/49#issuecomment-2161438989, maybe it will be a better solution

2024-06-11 19:13 UTC, notDmDrl commented on lib/src/pull_down_button.dart
> +  navigator ??= Navigator.of(context);
I don't like this reassignment here. Rather create a new local variable like this `final resolvedNavigator = navigator ?? Navigator.of(context);`

2024-06-11 19:13 UTC, notDmDrl commented on lib/src/pull_down_button.dart
> +  /// Custom navigator used to show the pull-down menu.
Could you also add what purpose this property has? Maybe mention that nested navigator use case?

2024-06-11 19:13 UTC, notDmDrl commented on lib/src/pull_down_button.dart
> +  navigator ??= Navigator.of(context);
Also see https://github.com/notDmDrl/pull_down_button/pull/49#issuecomment-2161438989

2024-06-13 14:58 UTC, notDmDrl commented
Hey @gborges9 

I've noticed that you decided to go with `rootNavigator` idea. I assume this solves the issue this PR tries to fix? 

If it does and this is ready to be merged please let me know, I will try to merge this ASAP

2024-08-03 01:52 UTC, andychucs commented
by the way, this PR also fixed a vertical offset problem in nested navigator.
<img width="648" alt="截屏2024-08-03 09 49 26" src="https://github.com/user-attachments/assets/a467eb86-0f89-4a85-abb7-670a11642084">
<img width="654" alt="截屏2024-08-03 09 49 48" src="https://github.com/user-attachments/assets/21e71273-6633-4bba-af9c-4e29cc62c409">

2024-08-03 11:25 UTC, notDmDrl commented
Hi @gborges9 

Sorry for the late response! I will close this PR as I implemented the `useRootNavigator` feature myself while working on update **0.10.0** (now live). You are, however, still credited for the change in the changelog 🙇‍♂️

Thanks again 😃

2024-08-03 11:25 UTC, closed without merging